#pragma once

# define REDEMPTION_PRAGMA(X) _Pragma(#X)

#if !defined(IN_IDE_PARSER) && (defined(__GNUC__) || defined(__clang__))
# define REDEMPTION_DIAGNOSTIC_PUSH REDEMPTION_PRAGMA(GCC diagnostic push)
# define REDEMPTION_DIAGNOSTIC_POP REDEMPTION_PRAGMA(GCC diagnostic pop)
# define REDEMPTION_DIAGNOSTIC_GCC_IGNORE(X) REDEMPTION_PRAGMA(GCC diagnostic ignored X)
# define REDEMPTION_DIAGNOSTIC_GCC_WARNING(X) REDEMPTION_PRAGMA(GCC diagnostic warning X)
# ifdef __clang__
#  define REDEMPTION_DIAGNOSTIC_GCC_ONLY_IGNORE(X)
#  define REDEMPTION_DIAGNOSTIC_CLANG_IGNORE REDEMPTION_DIAGNOSTIC_GCC_IGNORE
# else
#  define REDEMPTION_DIAGNOSTIC_GCC_ONLY_IGNORE REDEMPTION_DIAGNOSTIC_GCC_IGNORE
#  define REDEMPTION_DIAGNOSTIC_CLANG_IGNORE(X)
# endif
#else
# define REDEMPTION_DIAGNOSTIC_PUSH
# define REDEMPTION_DIAGNOSTIC_POP
# define REDEMPTION_DIAGNOSTIC_GCC_IGNORE(X)
# define REDEMPTION_DIAGNOSTIC_GCC_WARNING(X)
# define REDEMPTION_DIAGNOSTIC_GCC_ONLY_IGNORE(X)
# define REDEMPTION_DIAGNOSTIC_CLANG_IGNORE(X)
#endif
